spring:
  application:
    name: mall-admin
  datasource:
    username: root,
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MarketplaceBackstage?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
my:
  url: 123456789
server:
  port: 9000
